# Generated by Django 3.2.9 on 2022-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='BCD Brains', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
