# Generated by Django 3.2.9 on 2022-03-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_auto_20220328_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default=None, unique=True),
        ),
    ]
