# Generated by Django 3.2.9 on 2022-03-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0003_alter_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
