# Generated by Django 3.2.9 on 2022-03-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0004_rename_user_user1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='current_loc',
            field=models.CharField(max_length=254),
        ),
    ]
